### ISSUE TITLE
missing files in the menu help button

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.inkscape.Inkscape#4]
hi, i tried to access to options in the help button but appear this message:
"Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files"

I can not access to:
1.manual inkscape 
2.new in the version
3.etc

**Comment by matze** [comment]
Unfortunately, I cannot reproduce this behavior. For me a tab is opened to the [Inkscape manual](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/index.php) and the [release notes wiki page](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92).

@TingPing could this problem be caused by an older flatpak version?

**Comment by jurf** [comment]
@Lvaskz do you have `xdg-desktop-portal` installed? That sounds like the problem.

**Comment by Lvaskz** [comment]
Well, i don't know if i have installed. How can i do to know? and if not, how can install it?

**Comment by Lvaskz** [comment]
or maybe can update inkscape.flatpak?

**Comment by jurf** [comment]
@Lvaskz you need to install it with your distribution’s package manager. I doubt updating Inkscape will help you can try by running `flatpak update`.

**Comment by TingPing** [comment]
No information was given... so shot in the dark: `sudo apt install xdg-desktop-portal-gtk`

**Comment by Lvaskz** [comment]
yes, now it works
