### ISSUE TITLE
"Use symbolic icons" preference is not saved?

### ISSUE THREAD

**Issue by teohhanhui** [flathub/org.inkscape.Inkscape#80]
When I quit Inkscape and start it again, that preference is always reset...

**Comment by hfiguiere** [comment]
it works fine here.

**Comment by teohhanhui** [comment]
I'm using the system theme, instead of classic. Could that be the reason?

**Comment by nathanal** [comment]
I think we can close this issue. 

I replicate using a system theme instead of Adwaita, with Multicolor icon theme. My System theme is "Mint-Y-Dark-Orange". Strangely Mint-Y works fine. Testing on Linux Mint 20.

It also happens on Inkscape 1.1.1 (12cb7e2b4b, 2021-11-09), personal non-flatpak build, Linux Mint 20. This indicates it's an upstream issue.

Digging around, it would be https://gitlab.com/inkscape/inbox/-/issues/5676, which is fixed in 1.2-dev (can confirm testing with Inkscape 1.2-dev (8e60a08bcd, 2021-12-04))

**Comment by hfiguiere** [comment]
we'll likely get 1.2 on the beta channel when it's beta.
